### ISSUE TITLE
Rollup not working correctly for @propelauth/cloudflare-worker

### ISSUE THREAD

**Issue by FraBle** [PropelAuth/node#48]
It appears the rollup/build config is not working correctly. The created output (`dist`) uses the node runtime of `jose` instead of the browser runtime. This can be observed browsing the code on npmjs: https://www.npmjs.com/package/@propelauth/cloudflare-worker?activeTab=code

**Comment by FraBle** [comment]
It appears to be caused by depending on `@propelauth/node` now. I browsed through the code on npmjs and versions <2.1.3 are fine. So, the merge into this repo and introducing `@propelauth/node` as a dependency now caused the `node:` imports, which mostly come from then `node` runtime of `jose`.

```
import { Buffer } from 'node:buffer';
import * as crypto from 'node:crypto';
import { KeyObject, createPublicKey, constants, createSecretKey } from 'node:crypto';
import * as util from 'node:util';
import { promisify } from 'node:util';
```

When I change the `rollup.config.js` of `@propelauth/node` to match the `resolve` of `@propelauth/cloudflare-worker` with...

```js
        resolve({
            extensions,
            exportConditions: ["browser", "worker"],
            browser: true,
        }),
```
... the imports above are gone from the `dist` output.

**Comment by andrew-propelauth** [comment]
Thanks so much for the detailed report and fix! We really appreciate it - give us a little bit of time to test and then we can get it out.

**Comment by FraBle** [comment]
Happy to help! @andrew-propelauth when do you think you might get a chance to review the issue and PR?

**Comment by andrew-propelauth** [comment]
Should be fixed by EOD today. We took a slightly different approach in the end, which was to split out Cloudflare worker support into it's own separate package (@propelauth/cloudflare-worker): https://github.com/PropelAuth/node/pull/50

We were a little worried about the IDE experience since it was easy for a developer to accidentally import the wrong type / initialization function when they were both in the same package.

**Comment by FraBle** [comment]
Ah, that makes sense 👍

For context: I'm working on a hono middleware (https://github.com/honojs/middleware) for PropelAuth and was running into the original issue when trying to build an example app.

**Comment by andrew-propelauth** [comment]
New version should be live and we have docs available here: https://docs.propelauth.com/reference/backend-apis/cloudflare-workers

Let us know if you run into any issues and thanks again for reporting!
